# Generated by Django 4.2.13 on 2024-07-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
        ('cadastro_seller', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='usuario',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='contato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='contatos.contato'),
            preserve_default=False,
        ),
    ]
