# Generated by Django 4.2.13 on 2024-07-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
        ('cadastro_seller', '0003_remove_oportunidade_usuario_oportunidade_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='contato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='contatos.contato'),
        ),
    ]
