# Generated by Django 4.2.13 on 2024-07-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0004_alter_oportunidade_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_seller.empresa'),
        ),
    ]
