# Generated by Django 4.2.13 on 2024-07-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0006_alter_tarefa_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='empresa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_tarefa', to='cadastro_seller.empresa'),
        ),
    ]
