# Generated by Django 4.2.13 on 2024-07-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0007_alter_tarefa_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidade',
            old_name='vendedor',
            new_name='usuario',
        ),
    ]
