# Generated by Django 4.2.13 on 2024-07-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0008_rename_vendedor_oportunidade_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Probabilidade'),
        ),
    ]
