# Generated by Django 4.2.13 on 2024-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0009_alter_oportunidade_probabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Probabilidade'),
        ),
    ]
