# Generated by Django 4.2.13 on 2024-07-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0010_alter_oportunidade_probabilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='contato',
        ),
    ]
