# Generated by Django 4.2.13 on 2024-07-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_remove_contato_empresa_contato_oportunidade'),
        ('cadastro_seller', '0011_remove_oportunidade_contato_remove_tarefa_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='ontato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contatos.contato'),
            preserve_default=False,
        ),
    ]
