# Generated by Django 4.2.13 on 2024-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0013_rename_ontato_tarefa_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='taxa_comissao',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Taxa de Comissão'),
        ),
    ]
