# Generated by Django 4.2.13 on 2024-07-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0014_alter_oportunidade_taxa_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
