# Generated by Django 4.2.13 on 2024-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0015_tarefa_data_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
