# Generated by Django 4.2.13 on 2024-07-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0018_tarefa_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='horario_incio',
            new_name='horario_inicio',
        ),
    ]
