# Generated by Django 4.2.13 on 2024-07-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0019_rename_horario_incio_tarefa_horario_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='oportunidade',
            new_name='negocio',
        ),
    ]
