# Generated by Django 4.2.13 on 2024-07-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0011_remove_oportunidade_contato_remove_tarefa_contato'),
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='contato',
            name='cargo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro_seller.empresa'),
            preserve_default=False,
        ),
    ]
