# Generated by Django 4.2.13 on 2024-07-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_nome_completo_contato_nome_contato_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('TO', 'Tocantins'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], max_length=20),
        ),
    ]
