# Generated by Django 4.2.13 on 2024-07-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0011_remove_oportunidade_contato_remove_tarefa_contato'),
        ('contatos', '0004_alter_contato_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='empresa',
        ),
        migrations.AddField(
            model_name='contato',
            name='oportunidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro_seller.oportunidade'),
            preserve_default=False,
        ),
    ]
