# Generated by Django 4.2.13 on 2024-07-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_remove_contato_empresa_contato_oportunidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='oportunidade',
            new_name='negocio',
        ),
    ]
