# Generated by Django 4.2.13 on 2024-08-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_seller', '0022_alter_empresa_agencia_alter_empresa_bairro_and_more'),
        ('contatos', '0007_contato_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro_seller.empresa'),
            preserve_default=False,
        ),
    ]
