# Generated by Django 4.2.13 on 2024-07-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=194, unique=True, verbose_name='E-mail do usuário')),
                ('foto_perfil', models.FileField(blank=True, upload_to='Imagem perfil/')),
                ('telefone', models.CharField(blank=True, max_length=12)),
                ('cidade', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('funcao', models.CharField(blank=True, choices=[('Comercial', 'Comercial'), ('Marketing', 'MArketing'), ('Financeiro', 'Financeiro'), ('Outros', 'Outros')], max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário é da equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
